#!/usr/bin/env bash

# HOOK: BEFORE BUILD
# This hook runs each time CI Joe is initiating a build, after git reset.

# Symlinking project specific database.yml
ln -s ../../database.yml config/database.yml

# Bootstrap the test DB
RAILS_ENV=test rake db:create

# Temporary solution since, we don't have a schema.rb commited
RAILS_ENV=test rake db:migrate

# Perpare db changes in test environment
RAILS_ENV=test rake db:test:prepare
